import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/ui/Header";
import  Sidebar from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";



// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
      <html lang="en">
      
      <body>
        <div className="">
        <Header></Header>
        </div>
        
        <div className="flex min-h-screen">
          <Sidebar></Sidebar>
          <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide ">
        {children}
        </div>

        </div>
        
        <Toaster position="top-center"/>

        
      </body>
      </html>
    </ClerkProvider>
  );
}
